# Site settings
title: Galapagos Marine Genomics Project
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/galapagos-2" # the subpath of your site, e.g. /galapagos-2
url: "https://therkildsen-lab.github.io" # the base hostname & protocol for your site
author: Copyright © 2025 - Galapagos Marine Genomics Project
lang: en_US

# Build settings
safe: true # always true on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
